services: 
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  #  backend:
  #    build: 
  #      context: ./server
  #      dockerfile: Dockerfile
  #    depends_on:
  #      frontend:
  #        condition: service_healthy
  #    ports:
  #      - "3001:3001"
  #    expose:
  #      - "3001"
  database:
      build: 
        context: ./database
        dockerfile: Dockerfile
      ports:
        - "8091-8096:8091-8096"
        - "11210-11211:11210-11211"
      expose:
        - "8091-8096"
        - "11210-11211"
      extra_hosts:
      - "host.docker.internal:host-gateway"
