services: 
  frontend: 
    build: 
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app-net
    depends_on:
      - database
      - backend
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 20s
      timeout: 10s
      start_period: 10s
      retries: 5
    networks:
      - app-net
    expose:
      - "3001"
  database:
      build: 
        context: ./database
        dockerfile: Dockerfile
      ports:
        - "8091"
      expose:
        - "8091-8096"
        - "11210-11211"
      networks:
        - app-net
      healthcheck:
        test: ["CMD", "curl", "-f", "-u", "admin:password", "http://localhost:8091/pools"]
        interval: 20s
        timeout: 10s
        retries: 10

networks:  
  app-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

